name: Build & Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Updating Hugo sources
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Initialize Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Buildung Static Files
        run: hugo --minify

      - name: Deploying to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: eonyx/eonyx.github.io
          publish_branch: main
          publish_dir: ./public
